package com.example.practisejdbl69.domain;

public enum Genre {
    FICTION, NON_FICTION, SCIENCE_FICTION, HORROR, ROMANCE, DRAMA, COMEDY, THRILLER, ACTION, ADVENTURE, ANIMATION, BIOGRAPHY, CLASSIC, CRIME, DOCUMENTARY, FAMILY, HISTORY, MUSIC, MYSTERY, POLITICAL, ROMANTIC, SATIRE, SCIENCE, SPORTS, TELEVISION, WESTERN;
}
